#!/bin/bash

export PATH=`git rev-parse --git-dir`/../tools/:$PATH

clang-format --extensions cpp,hpp,c,h --style file -v

rc=$?
if [[ $rc == 33 ]]
then
 echo "Nothing needs to be reformatted!"
 exit 0
fi

echo -e "Would you like to continue to commit (y/n): \c"

# Make sure under any mode, we can read user input.
exec < /dev/tty
read cont

if [ "$cont" == "y" ]
then
 exit 0
fi

exit 1