classdef raw_sensor_object_data_msg < ros.Message
    %raw_sensor_object_data_msg MATLAB implementation of ecmc/raw_sensor_object_data_msg
    %   This class was automatically generated by
    %   ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2020 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'ecmc/raw_sensor_object_data_msg' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '4c9f4f782814b2d328e77842c4faa779' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        StdMsgsHeaderClass = ros.msg.internal.MessageFactory.getClassForType('std_msgs/Header') % Dispatch to MATLAB class for message type std_msgs/Header
    end
    
    properties (Dependent)
        Header
        RadarNum
        NumObjects
        AccelX
        VelX
        PosX
        PosY
        ExistProb
        Valid
    end
    
    properties (Access = protected)
        Cache = struct('Header', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'AccelX', 'ExistProb', 'Header', 'NumObjects', 'PosX', 'PosY', 'RadarNum', 'Valid', 'VelX'} % List of non-constant message properties
        ROSPropertyList = {'accel_x', 'exist_prob', 'header', 'num_objects', 'pos_x', 'pos_y', 'radar_num', 'valid', 'vel_x'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = raw_sensor_object_data_msg(msg)
            %raw_sensor_object_data_msg Construct the message object raw_sensor_object_data_msg
            import com.mathworks.toolbox.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('ros:mlros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('ros:mlros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('ros:mlros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function header = get.Header(obj)
            %get.Header Get the value for property Header
            if isempty(obj.Cache.Header)
                obj.Cache.Header = feval(obj.StdMsgsHeaderClass, obj.JavaMessage.getHeader);
            end
            header = obj.Cache.Header;
        end
        
        function set.Header(obj, header)
            %set.Header Set the value for property Header
            validateattributes(header, {obj.StdMsgsHeaderClass}, {'nonempty', 'scalar'}, 'raw_sensor_object_data_msg', 'Header');
            
            obj.JavaMessage.setHeader(header.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Header)
                obj.Cache.Header.setJavaObject(header.getJavaObject);
            end
        end
        
        function radarnum = get.RadarNum(obj)
            %get.RadarNum Get the value for property RadarNum
            radarnum = typecast(int8(obj.JavaMessage.getRadarNum), 'uint8');
        end
        
        function set.RadarNum(obj, radarnum)
            %set.RadarNum Set the value for property RadarNum
            validateattributes(radarnum, {'numeric'}, {'nonempty', 'scalar'}, 'raw_sensor_object_data_msg', 'RadarNum');
            
            obj.JavaMessage.setRadarNum(radarnum);
        end
        
        function numobjects = get.NumObjects(obj)
            %get.NumObjects Get the value for property NumObjects
            numobjects = typecast(int8(obj.JavaMessage.getNumObjects), 'uint8');
        end
        
        function set.NumObjects(obj, numobjects)
            %set.NumObjects Set the value for property NumObjects
            validateattributes(numobjects, {'numeric'}, {'nonempty', 'scalar'}, 'raw_sensor_object_data_msg', 'NumObjects');
            
            obj.JavaMessage.setNumObjects(numobjects);
        end
        
        function accelx = get.AccelX(obj)
            %get.AccelX Get the value for property AccelX
            javaArray = obj.JavaMessage.getAccelX;
            array = obj.readJavaArray(javaArray, 'double');
            accelx = double(array);
        end
        
        function set.AccelX(obj, accelx)
            %set.AccelX Set the value for property AccelX
            if ~isvector(accelx) && isempty(accelx)
                % Allow empty [] input
                accelx = double.empty(0,1);
            end
            
            validateattributes(accelx, {'numeric'}, {'vector'}, 'raw_sensor_object_data_msg', 'AccelX');
            
            javaArray = obj.JavaMessage.getAccelX;
            array = obj.writeJavaArray(accelx, javaArray, 'double');
            obj.JavaMessage.setAccelX(array);
        end
        
        function velx = get.VelX(obj)
            %get.VelX Get the value for property VelX
            javaArray = obj.JavaMessage.getVelX;
            array = obj.readJavaArray(javaArray, 'double');
            velx = double(array);
        end
        
        function set.VelX(obj, velx)
            %set.VelX Set the value for property VelX
            if ~isvector(velx) && isempty(velx)
                % Allow empty [] input
                velx = double.empty(0,1);
            end
            
            validateattributes(velx, {'numeric'}, {'vector'}, 'raw_sensor_object_data_msg', 'VelX');
            
            javaArray = obj.JavaMessage.getVelX;
            array = obj.writeJavaArray(velx, javaArray, 'double');
            obj.JavaMessage.setVelX(array);
        end
        
        function posx = get.PosX(obj)
            %get.PosX Get the value for property PosX
            javaArray = obj.JavaMessage.getPosX;
            array = obj.readJavaArray(javaArray, 'double');
            posx = double(array);
        end
        
        function set.PosX(obj, posx)
            %set.PosX Set the value for property PosX
            if ~isvector(posx) && isempty(posx)
                % Allow empty [] input
                posx = double.empty(0,1);
            end
            
            validateattributes(posx, {'numeric'}, {'vector'}, 'raw_sensor_object_data_msg', 'PosX');
            
            javaArray = obj.JavaMessage.getPosX;
            array = obj.writeJavaArray(posx, javaArray, 'double');
            obj.JavaMessage.setPosX(array);
        end
        
        function posy = get.PosY(obj)
            %get.PosY Get the value for property PosY
            javaArray = obj.JavaMessage.getPosY;
            array = obj.readJavaArray(javaArray, 'double');
            posy = double(array);
        end
        
        function set.PosY(obj, posy)
            %set.PosY Set the value for property PosY
            if ~isvector(posy) && isempty(posy)
                % Allow empty [] input
                posy = double.empty(0,1);
            end
            
            validateattributes(posy, {'numeric'}, {'vector'}, 'raw_sensor_object_data_msg', 'PosY');
            
            javaArray = obj.JavaMessage.getPosY;
            array = obj.writeJavaArray(posy, javaArray, 'double');
            obj.JavaMessage.setPosY(array);
        end
        
        function existprob = get.ExistProb(obj)
            %get.ExistProb Get the value for property ExistProb
            javaArray = obj.JavaMessage.getExistProb;
            array = obj.readJavaArray(javaArray, 'double');
            existprob = double(array);
        end
        
        function set.ExistProb(obj, existprob)
            %set.ExistProb Set the value for property ExistProb
            if ~isvector(existprob) && isempty(existprob)
                % Allow empty [] input
                existprob = double.empty(0,1);
            end
            
            validateattributes(existprob, {'numeric'}, {'vector'}, 'raw_sensor_object_data_msg', 'ExistProb');
            
            javaArray = obj.JavaMessage.getExistProb;
            array = obj.writeJavaArray(existprob, javaArray, 'double');
            obj.JavaMessage.setExistProb(array);
        end
        
        function valid = get.Valid(obj)
            %get.Valid Get the value for property Valid
            javaArray = obj.JavaMessage.getValid;
            array = obj.readJavaArray(javaArray, 'logical');
            valid = logical(array);
        end
        
        function set.Valid(obj, valid)
            %set.Valid Set the value for property Valid
            if ~isvector(valid) && isempty(valid)
                % Allow empty [] input
                valid = logical.empty(0,1);
            end
            
            validateattributes(valid, {'logical', 'numeric'}, {'vector'}, 'raw_sensor_object_data_msg', 'Valid');
            
            javaArray = obj.JavaMessage.getValid;
            array = obj.writeJavaArray(valid, javaArray, 'logical');
            obj.JavaMessage.setValid(array);
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Header = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.RadarNum = obj.RadarNum;
            cpObj.NumObjects = obj.NumObjects;
            cpObj.AccelX = obj.AccelX;
            cpObj.VelX = obj.VelX;
            cpObj.PosX = obj.PosX;
            cpObj.PosY = obj.PosY;
            cpObj.ExistProb = obj.ExistProb;
            cpObj.Valid = obj.Valid;
            
            % Recursively copy compound properties
            cpObj.Header = copy(obj.Header);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.RadarNum = strObj.RadarNum;
            obj.NumObjects = strObj.NumObjects;
            obj.AccelX = strObj.AccelX;
            obj.VelX = strObj.VelX;
            obj.PosX = strObj.PosX;
            obj.PosY = strObj.PosY;
            obj.ExistProb = strObj.ExistProb;
            obj.Valid = strObj.Valid;
            obj.Header = feval([obj.StdMsgsHeaderClass '.loadobj'], strObj.Header);
        end
    end
    
    methods (Access = ?ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.RadarNum = obj.RadarNum;
            strObj.NumObjects = obj.NumObjects;
            strObj.AccelX = obj.AccelX;
            strObj.VelX = obj.VelX;
            strObj.PosX = obj.PosX;
            strObj.PosY = obj.PosY;
            strObj.ExistProb = obj.ExistProb;
            strObj.Valid = obj.Valid;
            strObj.Header = saveobj(obj.Header);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.custom.msggen.ecmc.raw_sensor_object_data_msg.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = ros.custom.msggen.ecmc.raw_sensor_object_data_msg;
            obj.reload(strObj);
        end
    end
end
