classdef sensor_diagnostic_data_msg < ros.Message
    %sensor_diagnostic_data_msg MATLAB implementation of can_tx_rx/sensor_diagnostic_data_msg
    %   This class was automatically generated by
    %   ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2020 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'can_tx_rx/sensor_diagnostic_data_msg' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '9037d8e808d655c0ded14a5d412957bc' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        StdMsgsHeaderClass = ros.msg.internal.MessageFactory.getClassForType('std_msgs/Header') % Dispatch to MATLAB class for message type std_msgs/Header
    end
    
    properties (Dependent)
        Header
        RadarDiagInput
        RadarInfo
    end
    
    properties (Access = protected)
        Cache = struct('Header', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Header', 'RadarDiagInput', 'RadarInfo'} % List of non-constant message properties
        ROSPropertyList = {'header', 'radar_diag_input', 'radar_info'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = sensor_diagnostic_data_msg(msg)
            %sensor_diagnostic_data_msg Construct the message object sensor_diagnostic_data_msg
            import com.mathworks.toolbox.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('ros:mlros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('ros:mlros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('ros:mlros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function header = get.Header(obj)
            %get.Header Get the value for property Header
            if isempty(obj.Cache.Header)
                obj.Cache.Header = feval(obj.StdMsgsHeaderClass, obj.JavaMessage.getHeader);
            end
            header = obj.Cache.Header;
        end
        
        function set.Header(obj, header)
            %set.Header Set the value for property Header
            validateattributes(header, {obj.StdMsgsHeaderClass}, {'nonempty', 'scalar'}, 'sensor_diagnostic_data_msg', 'Header');
            
            obj.JavaMessage.setHeader(header.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Header)
                obj.Cache.Header.setJavaObject(header.getJavaObject);
            end
        end
        
        function radardiaginput = get.RadarDiagInput(obj)
            %get.RadarDiagInput Get the value for property RadarDiagInput
            javaArray = obj.JavaMessage.getRadarDiagInput;
            array = obj.readJavaArray(javaArray, 'uint8');
            radardiaginput = uint8(array);
        end
        
        function set.RadarDiagInput(obj, radardiaginput)
            %set.RadarDiagInput Set the value for property RadarDiagInput
            if ~isvector(radardiaginput) && isempty(radardiaginput)
                % Allow empty [] input
                radardiaginput = uint8.empty(0,1);
            end
            
            validateattributes(radardiaginput, {'numeric'}, {'vector'}, 'sensor_diagnostic_data_msg', 'RadarDiagInput');
            
            javaArray = obj.JavaMessage.getRadarDiagInput;
            array = obj.writeJavaArray(radardiaginput, javaArray, 'uint8');
            obj.JavaMessage.setRadarDiagInput(array);
        end
        
        function radarinfo = get.RadarInfo(obj)
            %get.RadarInfo Get the value for property RadarInfo
            javaArray = obj.JavaMessage.getRadarInfo;
            array = obj.readJavaArray(javaArray, 'uint8');
            radarinfo = uint8(array);
        end
        
        function set.RadarInfo(obj, radarinfo)
            %set.RadarInfo Set the value for property RadarInfo
            if ~isvector(radarinfo) && isempty(radarinfo)
                % Allow empty [] input
                radarinfo = uint8.empty(0,1);
            end
            
            validateattributes(radarinfo, {'numeric'}, {'vector'}, 'sensor_diagnostic_data_msg', 'RadarInfo');
            
            javaArray = obj.JavaMessage.getRadarInfo;
            array = obj.writeJavaArray(radarinfo, javaArray, 'uint8');
            obj.JavaMessage.setRadarInfo(array);
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Header = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.RadarDiagInput = obj.RadarDiagInput;
            cpObj.RadarInfo = obj.RadarInfo;
            
            % Recursively copy compound properties
            cpObj.Header = copy(obj.Header);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.RadarDiagInput = strObj.RadarDiagInput;
            obj.RadarInfo = strObj.RadarInfo;
            obj.Header = feval([obj.StdMsgsHeaderClass '.loadobj'], strObj.Header);
        end
    end
    
    methods (Access = ?ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.RadarDiagInput = obj.RadarDiagInput;
            strObj.RadarInfo = obj.RadarInfo;
            strObj.Header = saveobj(obj.Header);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.custom.msggen.can_tx_rx.sensor_diagnostic_data_msg.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = ros.custom.msggen.can_tx_rx.sensor_diagnostic_data_msg;
            obj.reload(strObj);
        end
    end
end
