/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 32.20.3 Tue Jun  2 20:55:50 2020.
 */

#include <string.h>

#include "ext_log_data.h"
#include "lcc_protocol.h"

int ext_log_data_ahbc_gradual_data_b_pack(
    uint8_t *dst_p,
    const struct ext_log_data_ahbc_gradual_data_b_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u8(src_p->st_bndry_dom_bot_ngl_hlb, 0u, 0x03u);
    dst_p[0] |= pack_left_shift_u8(src_p->st_bndry_dom_ngl_lh_hlb, 2u, 0x0cu);
    dst_p[0] |= pack_left_shift_u8(src_p->st_bndry_dom_ngl_rh_hlb, 4u, 0x30u);
    dst_p[0] |= pack_left_shift_u8(src_p->st_obj_dist_hlb, 6u, 0xc0u);
    dst_p[1] |= pack_left_shift_u8(src_p->left_target_change, 0u, 0x01u);
    dst_p[1] |= pack_left_shift_u8(src_p->right_target_change, 1u, 0x02u);
    dst_p[1] |= pack_left_shift_u8(src_p->too_many_cars, 2u, 0x04u);
    dst_p[1] |= pack_left_shift_u8(src_p->busy_scene, 3u, 0x08u);

    return (2);
}

int ext_log_data_ahbc_gradual_data_b_unpack(
    struct ext_log_data_ahbc_gradual_data_b_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->st_bndry_dom_bot_ngl_hlb |= unpack_right_shift_u8(src_p[0], 0u, 0x03u);
    dst_p->st_bndry_dom_ngl_lh_hlb |= unpack_right_shift_u8(src_p[0], 2u, 0x0cu);
    dst_p->st_bndry_dom_ngl_rh_hlb |= unpack_right_shift_u8(src_p[0], 4u, 0x30u);
    dst_p->st_obj_dist_hlb |= unpack_right_shift_u8(src_p[0], 6u, 0xc0u);
    dst_p->left_target_change |= unpack_right_shift_u8(src_p[1], 0u, 0x01u);
    dst_p->right_target_change |= unpack_right_shift_u8(src_p[1], 1u, 0x02u);
    dst_p->too_many_cars |= unpack_right_shift_u8(src_p[1], 2u, 0x04u);
    dst_p->busy_scene |= unpack_right_shift_u8(src_p[1], 3u, 0x08u);

    return (0);
}

uint8_t ext_log_data_ahbc_gradual_data_b_st_bndry_dom_bot_ngl_hlb_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_ahbc_gradual_data_b_st_bndry_dom_bot_ngl_hlb_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_ahbc_gradual_data_b_st_bndry_dom_bot_ngl_hlb_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t ext_log_data_ahbc_gradual_data_b_st_bndry_dom_ngl_lh_hlb_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_ahbc_gradual_data_b_st_bndry_dom_ngl_lh_hlb_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_ahbc_gradual_data_b_st_bndry_dom_ngl_lh_hlb_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t ext_log_data_ahbc_gradual_data_b_st_bndry_dom_ngl_rh_hlb_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_ahbc_gradual_data_b_st_bndry_dom_ngl_rh_hlb_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_ahbc_gradual_data_b_st_bndry_dom_ngl_rh_hlb_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t ext_log_data_ahbc_gradual_data_b_st_obj_dist_hlb_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_ahbc_gradual_data_b_st_obj_dist_hlb_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_ahbc_gradual_data_b_st_obj_dist_hlb_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t ext_log_data_ahbc_gradual_data_b_left_target_change_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_ahbc_gradual_data_b_left_target_change_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_ahbc_gradual_data_b_left_target_change_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ext_log_data_ahbc_gradual_data_b_right_target_change_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_ahbc_gradual_data_b_right_target_change_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_ahbc_gradual_data_b_right_target_change_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ext_log_data_ahbc_gradual_data_b_too_many_cars_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_ahbc_gradual_data_b_too_many_cars_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_ahbc_gradual_data_b_too_many_cars_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ext_log_data_ahbc_gradual_data_b_busy_scene_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_ahbc_gradual_data_b_busy_scene_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_ahbc_gradual_data_b_busy_scene_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int ext_log_data_lane_details_pack(
    uint8_t *dst_p,
    const struct ext_log_data_lane_details_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->position_in_lanes, 4u, 0xf0u);
    dst_p[0] |= pack_left_shift_u8(src_p->number_of_lanes, 0u, 0x0fu);
    dst_p[3] |= pack_left_shift_u8(src_p->left_guard_rail, 2u, 0x04u);
    dst_p[3] |= pack_left_shift_u8(src_p->right_guard_rail, 3u, 0x08u);
    dst_p[3] |= pack_left_shift_u8(src_p->construction_area, 4u, 0x10u);
    dst_p[3] |= pack_left_shift_u8(src_p->right_ldw_availability, 5u, 0x20u);
    dst_p[3] |= pack_left_shift_u8(src_p->left_ldw_availability, 6u, 0x40u);
    dst_p[4] |= pack_left_shift_u16(src_p->yaw_angle, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->yaw_angle, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->pitch_angle, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->pitch_angle, 8u, 0xffu);

    return (8);
}

int ext_log_data_lane_details_unpack(
    struct ext_log_data_lane_details_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->position_in_lanes |= unpack_right_shift_u8(src_p[0], 4u, 0xf0u);
    dst_p->number_of_lanes |= unpack_right_shift_u8(src_p[0], 0u, 0x0fu);
    dst_p->left_guard_rail |= unpack_right_shift_u8(src_p[3], 2u, 0x04u);
    dst_p->right_guard_rail |= unpack_right_shift_u8(src_p[3], 3u, 0x08u);
    dst_p->construction_area |= unpack_right_shift_u8(src_p[3], 4u, 0x10u);
    dst_p->right_ldw_availability |= unpack_right_shift_u8(src_p[3], 5u, 0x20u);
    dst_p->left_ldw_availability |= unpack_right_shift_u8(src_p[3], 6u, 0x40u);
    dst_p->yaw_angle |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->yaw_angle |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->pitch_angle |= unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->pitch_angle |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

uint8_t ext_log_data_lane_details_position_in_lanes_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_lane_details_position_in_lanes_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_lane_details_position_in_lanes_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t ext_log_data_lane_details_number_of_lanes_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_lane_details_number_of_lanes_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_lane_details_number_of_lanes_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t ext_log_data_lane_details_left_guard_rail_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_lane_details_left_guard_rail_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_lane_details_left_guard_rail_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ext_log_data_lane_details_right_guard_rail_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_lane_details_right_guard_rail_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_lane_details_right_guard_rail_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ext_log_data_lane_details_construction_area_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_lane_details_construction_area_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_lane_details_construction_area_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ext_log_data_lane_details_right_ldw_availability_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_lane_details_right_ldw_availability_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_lane_details_right_ldw_availability_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ext_log_data_lane_details_left_ldw_availability_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_lane_details_left_ldw_availability_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_lane_details_left_ldw_availability_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint16_t ext_log_data_lane_details_yaw_angle_encode(double value)
{
    return (uint16_t)((value - -31.999) / 0.000976563);
}

double ext_log_data_lane_details_yaw_angle_decode(uint16_t value)
{
    return (((double)value * 0.000976563) + -31.999);
}

bool ext_log_data_lane_details_yaw_angle_is_in_range(uint16_t value)
{
    return (value <= 65534u);
}

uint16_t ext_log_data_lane_details_pitch_angle_encode(double value)
{
    return (uint16_t)((value - -0.05) / 0.0000015259);
}

double ext_log_data_lane_details_pitch_angle_decode(uint16_t value)
{
    return (((double)value * 0.0000015259) + -0.05);
}

bool ext_log_data_lane_details_pitch_angle_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int ext_log_data_tsr_pack(
    uint8_t *dst_p,
    const struct ext_log_data_tsr_t *src_p,
    size_t size)
{
    uint8_t sign_position_y;
    uint8_t sign_position_z;

    if (size < 7u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 7);

    dst_p[0] |= pack_left_shift_u8(src_p->vision_only_sign_type, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->vision_only_supp_sign_type, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->sign_position_x, 0u, 0xffu);
    sign_position_y = (uint8_t)src_p->sign_position_y;
    dst_p[3] |= pack_left_shift_u8(sign_position_y, 0u, 0xffu);
    sign_position_z = (uint8_t)src_p->sign_position_z;
    dst_p[4] |= pack_left_shift_u8(sign_position_z, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->filter_type, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->no_entry_vision_status, 0u, 0x07u);

    return (7);
}

int ext_log_data_tsr_unpack(
    struct ext_log_data_tsr_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t sign_position_y;
    uint8_t sign_position_z;

    if (size < 7u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->vision_only_sign_type |= unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->vision_only_supp_sign_type |= unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->sign_position_x |= unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    sign_position_y = 0u;
    sign_position_y |= unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->sign_position_y = (int8_t)sign_position_y;
    sign_position_z = 0u;
    sign_position_z |= unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->sign_position_z = (int8_t)sign_position_z;
    dst_p->filter_type |= unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->no_entry_vision_status |= unpack_right_shift_u8(src_p[6], 0u, 0x07u);

    return (0);
}

uint8_t ext_log_data_tsr_vision_only_sign_type_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_tsr_vision_only_sign_type_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_tsr_vision_only_sign_type_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ext_log_data_tsr_vision_only_supp_sign_type_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_tsr_vision_only_supp_sign_type_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_tsr_vision_only_supp_sign_type_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ext_log_data_tsr_sign_position_x_encode(double value)
{
    return (uint8_t)(value / 0.5);
}

double ext_log_data_tsr_sign_position_x_decode(uint8_t value)
{
    return ((double)value * 0.5);
}

bool ext_log_data_tsr_sign_position_x_is_in_range(uint8_t value)
{
    return (value <= 244u);
}

int8_t ext_log_data_tsr_sign_position_y_encode(double value)
{
    return (int8_t)(value / 0.5);
}

double ext_log_data_tsr_sign_position_y_decode(int8_t value)
{
    return ((double)value * 0.5);
}

bool ext_log_data_tsr_sign_position_y_is_in_range(int8_t value)
{
    return ((value >= -64) && (value <= 62));
}

int8_t ext_log_data_tsr_sign_position_z_encode(double value)
{
    return (int8_t)(value / 0.5);
}

double ext_log_data_tsr_sign_position_z_decode(int8_t value)
{
    return ((double)value * 0.5);
}

bool ext_log_data_tsr_sign_position_z_is_in_range(int8_t value)
{
    return ((value >= -32) && (value <= 32));
}

uint8_t ext_log_data_tsr_filter_type_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_tsr_filter_type_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_tsr_filter_type_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ext_log_data_tsr_no_entry_vision_status_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_tsr_no_entry_vision_status_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_tsr_no_entry_vision_status_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

int ext_log_data_ahbc_gradual_pack(
    uint8_t *dst_p,
    const struct ext_log_data_ahbc_gradual_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 7);

    dst_p[0] |= pack_left_shift_u8(src_p->bndry_dom_bot_ngl_hlb, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->bndry_dom_ngl_lh_hlb, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->bndry_dom_ngl_lh_hlb, 8u, 0x0fu);
    dst_p[2] |= pack_left_shift_u16(src_p->bndry_dom_ngl_rh_hlb, 4u, 0xf0u);
    dst_p[3] |= pack_right_shift_u16(src_p->bndry_dom_ngl_rh_hlb, 4u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->obj_dist_hlb, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->obj_dist_hlb_right, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->obj_dist_hlb_left, 0u, 0xffu);

    return (7);
}

int ext_log_data_ahbc_gradual_unpack(
    struct ext_log_data_ahbc_gradual_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->bndry_dom_bot_ngl_hlb |= unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->bndry_dom_ngl_lh_hlb |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->bndry_dom_ngl_lh_hlb |= unpack_left_shift_u16(src_p[2], 8u, 0x0fu);
    dst_p->bndry_dom_ngl_rh_hlb |= unpack_right_shift_u16(src_p[2], 4u, 0xf0u);
    dst_p->bndry_dom_ngl_rh_hlb |= unpack_left_shift_u16(src_p[3], 4u, 0xffu);
    dst_p->obj_dist_hlb |= unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->obj_dist_hlb_right |= unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->obj_dist_hlb_left |= unpack_right_shift_u8(src_p[6], 0u, 0xffu);

    return (0);
}

uint8_t ext_log_data_ahbc_gradual_bndry_dom_bot_ngl_hlb_encode(double value)
{
    return (uint8_t)((value - -10.0) / 0.1);
}

double ext_log_data_ahbc_gradual_bndry_dom_bot_ngl_hlb_decode(uint8_t value)
{
    return (((double)value * 0.1) + -10.0);
}

bool ext_log_data_ahbc_gradual_bndry_dom_bot_ngl_hlb_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint16_t ext_log_data_ahbc_gradual_bndry_dom_ngl_lh_hlb_encode(double value)
{
    return (uint16_t)((value - -20.0) / 0.1);
}

double ext_log_data_ahbc_gradual_bndry_dom_ngl_lh_hlb_decode(uint16_t value)
{
    return (((double)value * 0.1) + -20.0);
}

bool ext_log_data_ahbc_gradual_bndry_dom_ngl_lh_hlb_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

uint16_t ext_log_data_ahbc_gradual_bndry_dom_ngl_rh_hlb_encode(double value)
{
    return (uint16_t)((value - -20.0) / 0.1);
}

double ext_log_data_ahbc_gradual_bndry_dom_ngl_rh_hlb_decode(uint16_t value)
{
    return (((double)value * 0.1) + -20.0);
}

bool ext_log_data_ahbc_gradual_bndry_dom_ngl_rh_hlb_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

uint8_t ext_log_data_ahbc_gradual_obj_dist_hlb_encode(double value)
{
    return (uint8_t)(value / 2.0);
}

double ext_log_data_ahbc_gradual_obj_dist_hlb_decode(uint8_t value)
{
    return ((double)value * 2.0);
}

bool ext_log_data_ahbc_gradual_obj_dist_hlb_is_in_range(uint8_t value)
{
    return (value <= 200u);
}

uint8_t ext_log_data_ahbc_gradual_obj_dist_hlb_right_encode(double value)
{
    return (uint8_t)(value / 2.0);
}

double ext_log_data_ahbc_gradual_obj_dist_hlb_right_decode(uint8_t value)
{
    return ((double)value * 2.0);
}

bool ext_log_data_ahbc_gradual_obj_dist_hlb_right_is_in_range(uint8_t value)
{
    return (value <= 200u);
}

uint8_t ext_log_data_ahbc_gradual_obj_dist_hlb_left_encode(double value)
{
    return (uint8_t)(value / 2.0);
}

double ext_log_data_ahbc_gradual_obj_dist_hlb_left_decode(uint8_t value)
{
    return ((double)value * 2.0);
}

bool ext_log_data_ahbc_gradual_obj_dist_hlb_left_is_in_range(uint8_t value)
{
    return (value <= 200u);
}

int ext_log_data_aws_display_pack(
    uint8_t *dst_p,
    const struct ext_log_data_aws_display_t *src_p,
    size_t size)
{
    uint8_t ped_fcw;
    uint8_t ped_in_dz;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->sound_type, 0u, 0x07u);
    dst_p[0] |= pack_left_shift_u8(src_p->dusk_time_indicator, 3u, 0x08u);
    dst_p[0] |= pack_left_shift_u8(src_p->night_time_indicator, 4u, 0x10u);
    dst_p[0] |= pack_left_shift_u8(src_p->suppress, 7u, 0x80u);
    dst_p[2] |= pack_left_shift_u8(src_p->headway_valid, 0u, 0x01u);
    dst_p[2] |= pack_left_shift_u8(src_p->headway_measurement, 1u, 0xfeu);
    dst_p[4] |= pack_left_shift_u8(src_p->lanes_on, 0u, 0x01u);
    dst_p[4] |= pack_left_shift_u8(src_p->left_ldw_on, 1u, 0x02u);
    dst_p[4] |= pack_left_shift_u8(src_p->right_ldw_on, 2u, 0x04u);
    dst_p[4] |= pack_left_shift_u8(src_p->fcw_on, 3u, 0x08u);
    dst_p[4] |= pack_left_shift_u8(src_p->left_crossing, 4u, 0x10u);
    dst_p[4] |= pack_left_shift_u8(src_p->right_crossing, 5u, 0x20u);
    dst_p[4] |= pack_left_shift_u8(src_p->maintenance, 6u, 0x40u);
    dst_p[4] |= pack_left_shift_u8(src_p->failsafe, 7u, 0x80u);
    ped_fcw = (uint8_t)src_p->ped_fcw;
    dst_p[5] |= pack_left_shift_u8(ped_fcw, 1u, 0x02u);
    ped_in_dz = (uint8_t)src_p->ped_in_dz;
    dst_p[5] |= pack_left_shift_u8(ped_in_dz, 2u, 0x04u);
    dst_p[7] |= pack_left_shift_u8(src_p->headway_warning_level, 0u, 0x03u);

    return (8);
}

int ext_log_data_aws_display_unpack(
    struct ext_log_data_aws_display_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t ped_fcw;
    uint8_t ped_in_dz;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->sound_type |= unpack_right_shift_u8(src_p[0], 0u, 0x07u);
    dst_p->dusk_time_indicator |= unpack_right_shift_u8(src_p[0], 3u, 0x08u);
    dst_p->night_time_indicator |= unpack_right_shift_u8(src_p[0], 4u, 0x10u);
    dst_p->suppress |= unpack_right_shift_u8(src_p[0], 7u, 0x80u);
    dst_p->headway_valid |= unpack_right_shift_u8(src_p[2], 0u, 0x01u);
    dst_p->headway_measurement |= unpack_right_shift_u8(src_p[2], 1u, 0xfeu);
    dst_p->lanes_on |= unpack_right_shift_u8(src_p[4], 0u, 0x01u);
    dst_p->left_ldw_on |= unpack_right_shift_u8(src_p[4], 1u, 0x02u);
    dst_p->right_ldw_on |= unpack_right_shift_u8(src_p[4], 2u, 0x04u);
    dst_p->fcw_on |= unpack_right_shift_u8(src_p[4], 3u, 0x08u);
    dst_p->left_crossing |= unpack_right_shift_u8(src_p[4], 4u, 0x10u);
    dst_p->right_crossing |= unpack_right_shift_u8(src_p[4], 5u, 0x20u);
    dst_p->maintenance |= unpack_right_shift_u8(src_p[4], 6u, 0x40u);
    dst_p->failsafe |= unpack_right_shift_u8(src_p[4], 7u, 0x80u);
    ped_fcw = 0u;
    ped_fcw |= unpack_right_shift_u8(src_p[5], 1u, 0x02u);

    if ((ped_fcw & (1u << 0)) != 0u) {
        ped_fcw |= 0xfeu;
    }

    dst_p->ped_fcw = (int8_t)ped_fcw;
    ped_in_dz = 0u;
    ped_in_dz |= unpack_right_shift_u8(src_p[5], 2u, 0x04u);

    if ((ped_in_dz & (1u << 0)) != 0u) {
        ped_in_dz |= 0xfeu;
    }

    dst_p->ped_in_dz = (int8_t)ped_in_dz;
    dst_p->headway_warning_level |= unpack_right_shift_u8(src_p[7], 0u, 0x03u);

    return (0);
}

uint8_t ext_log_data_aws_display_sound_type_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_aws_display_sound_type_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_aws_display_sound_type_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t ext_log_data_aws_display_dusk_time_indicator_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_aws_display_dusk_time_indicator_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_aws_display_dusk_time_indicator_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ext_log_data_aws_display_night_time_indicator_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_aws_display_night_time_indicator_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_aws_display_night_time_indicator_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ext_log_data_aws_display_suppress_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_aws_display_suppress_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_aws_display_suppress_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ext_log_data_aws_display_headway_valid_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_aws_display_headway_valid_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_aws_display_headway_valid_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ext_log_data_aws_display_headway_measurement_encode(double value)
{
    return (uint8_t)(value / 0.1);
}

double ext_log_data_aws_display_headway_measurement_decode(uint8_t value)
{
    return ((double)value * 0.1);
}

bool ext_log_data_aws_display_headway_measurement_is_in_range(uint8_t value)
{
    return (value <= 99u);
}

uint8_t ext_log_data_aws_display_lanes_on_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_aws_display_lanes_on_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_aws_display_lanes_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ext_log_data_aws_display_left_ldw_on_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_aws_display_left_ldw_on_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_aws_display_left_ldw_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ext_log_data_aws_display_right_ldw_on_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_aws_display_right_ldw_on_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_aws_display_right_ldw_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ext_log_data_aws_display_fcw_on_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_aws_display_fcw_on_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_aws_display_fcw_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ext_log_data_aws_display_left_crossing_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_aws_display_left_crossing_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_aws_display_left_crossing_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ext_log_data_aws_display_right_crossing_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_aws_display_right_crossing_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_aws_display_right_crossing_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ext_log_data_aws_display_maintenance_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_aws_display_maintenance_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_aws_display_maintenance_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ext_log_data_aws_display_failsafe_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_aws_display_failsafe_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_aws_display_failsafe_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int8_t ext_log_data_aws_display_ped_fcw_encode(double value)
{
    return (int8_t)(value);
}

double ext_log_data_aws_display_ped_fcw_decode(int8_t value)
{
    return ((double)value);
}

bool ext_log_data_aws_display_ped_fcw_is_in_range(int8_t value)
{
    return ((value >= -1) && (value <= 0));
}

int8_t ext_log_data_aws_display_ped_in_dz_encode(double value)
{
    return (int8_t)(value);
}

double ext_log_data_aws_display_ped_in_dz_decode(int8_t value)
{
    return ((double)value);
}

bool ext_log_data_aws_display_ped_in_dz_is_in_range(int8_t value)
{
    return ((value >= -1) && (value <= 0));
}

uint8_t ext_log_data_aws_display_headway_warning_level_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_aws_display_headway_warning_level_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_aws_display_headway_warning_level_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

int ext_log_data_obstacle_data_c_pack(
    uint8_t *dst_p,
    const struct ext_log_data_obstacle_data_c_t *src_p,
    size_t size)
{
    uint16_t object_accel_x;
    uint16_t obstacle_angle;
    uint16_t obstacle_angle_rate;
    uint16_t obstacle_scale_change;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    obstacle_angle_rate = (uint16_t)src_p->obstacle_angle_rate;
    dst_p[0] |= pack_left_shift_u16(obstacle_angle_rate, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(obstacle_angle_rate, 8u, 0xffu);
    obstacle_scale_change = (uint16_t)src_p->obstacle_scale_change;
    dst_p[2] |= pack_left_shift_u16(obstacle_scale_change, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(obstacle_scale_change, 8u, 0xffu);
    object_accel_x = (uint16_t)src_p->object_accel_x;
    dst_p[4] |= pack_left_shift_u16(object_accel_x, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(object_accel_x, 8u, 0x03u);
    dst_p[5] |= pack_left_shift_u8(src_p->obstacle_replaced, 4u, 0x10u);
    obstacle_angle = (uint16_t)src_p->obstacle_angle;
    dst_p[6] |= pack_left_shift_u16(obstacle_angle, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(obstacle_angle, 8u, 0xffu);

    return (8);
}

int ext_log_data_obstacle_data_c_unpack(
    struct ext_log_data_obstacle_data_c_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t object_accel_x;
    uint16_t obstacle_angle;
    uint16_t obstacle_angle_rate;
    uint16_t obstacle_scale_change;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    obstacle_angle_rate = 0u;
    obstacle_angle_rate |= unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    obstacle_angle_rate |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->obstacle_angle_rate = (int16_t)obstacle_angle_rate;
    obstacle_scale_change = 0u;
    obstacle_scale_change |= unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    obstacle_scale_change |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->obstacle_scale_change = (int16_t)obstacle_scale_change;
    object_accel_x = 0u;
    object_accel_x |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    object_accel_x |= unpack_left_shift_u16(src_p[5], 8u, 0x03u);

    if ((object_accel_x & (1u << 9)) != 0u) {
        object_accel_x |= 0xfc00u;
    }

    dst_p->object_accel_x = (int16_t)object_accel_x;
    dst_p->obstacle_replaced |= unpack_right_shift_u8(src_p[5], 4u, 0x10u);
    obstacle_angle = 0u;
    obstacle_angle |= unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    obstacle_angle |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->obstacle_angle = (int16_t)obstacle_angle;

    return (0);
}

int16_t ext_log_data_obstacle_data_c_obstacle_angle_rate_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double ext_log_data_obstacle_data_c_obstacle_angle_rate_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool ext_log_data_obstacle_data_c_obstacle_angle_rate_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t ext_log_data_obstacle_data_c_obstacle_scale_change_encode(double value)
{
    return (int16_t)(value / 0.0002);
}

double ext_log_data_obstacle_data_c_obstacle_scale_change_decode(int16_t value)
{
    return ((double)value * 0.0002);
}

bool ext_log_data_obstacle_data_c_obstacle_scale_change_is_in_range(int16_t value)
{
    return (value >= -32767);
}

int16_t ext_log_data_obstacle_data_c_object_accel_x_encode(double value)
{
    return (int16_t)(value / 0.03);
}

double ext_log_data_obstacle_data_c_object_accel_x_decode(int16_t value)
{
    return ((double)value * 0.03);
}

bool ext_log_data_obstacle_data_c_object_accel_x_is_in_range(int16_t value)
{
    return ((value >= -499) && (value <= 499));
}

uint8_t ext_log_data_obstacle_data_c_obstacle_replaced_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_obstacle_data_c_obstacle_replaced_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_obstacle_data_c_obstacle_replaced_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int16_t ext_log_data_obstacle_data_c_obstacle_angle_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double ext_log_data_obstacle_data_c_obstacle_angle_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool ext_log_data_obstacle_data_c_obstacle_angle_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int ext_log_data_obstacle_data_b_pack(
    uint8_t *dst_p,
    const struct ext_log_data_obstacle_data_b_t *src_p,
    size_t size)
{
    uint16_t radar_vel_x;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->obstacle_length, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->obstacle_width, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->obstacle_age, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->obstacle_lane, 0u, 0x03u);
    dst_p[3] |= pack_left_shift_u8(src_p->cipv_flag, 2u, 0x04u);
    dst_p[3] |= pack_left_shift_u16(src_p->radar_pos_x, 4u, 0xf0u);
    dst_p[4] |= pack_right_shift_u16(src_p->radar_pos_x, 4u, 0xffu);
    radar_vel_x = (uint16_t)src_p->radar_vel_x;
    dst_p[5] |= pack_left_shift_u16(radar_vel_x, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(radar_vel_x, 8u, 0x0fu);
    dst_p[6] |= pack_left_shift_u8(src_p->radar_match_confidence, 4u, 0x70u);
    dst_p[7] |= pack_left_shift_u8(src_p->matched_radar_id, 0u, 0x7fu);

    return (8);
}

int ext_log_data_obstacle_data_b_unpack(
    struct ext_log_data_obstacle_data_b_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t radar_vel_x;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->obstacle_length |= unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->obstacle_width |= unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->obstacle_age |= unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->obstacle_lane |= unpack_right_shift_u8(src_p[3], 0u, 0x03u);
    dst_p->cipv_flag |= unpack_right_shift_u8(src_p[3], 2u, 0x04u);
    dst_p->radar_pos_x |= unpack_right_shift_u16(src_p[3], 4u, 0xf0u);
    dst_p->radar_pos_x |= unpack_left_shift_u16(src_p[4], 4u, 0xffu);
    radar_vel_x = 0u;
    radar_vel_x |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    radar_vel_x |= unpack_left_shift_u16(src_p[6], 8u, 0x0fu);

    if ((radar_vel_x & (1u << 11)) != 0u) {
        radar_vel_x |= 0xf000u;
    }

    dst_p->radar_vel_x = (int16_t)radar_vel_x;
    dst_p->radar_match_confidence |= unpack_right_shift_u8(src_p[6], 4u, 0x70u);
    dst_p->matched_radar_id |= unpack_right_shift_u8(src_p[7], 0u, 0x7fu);

    return (0);
}

uint8_t ext_log_data_obstacle_data_b_obstacle_length_encode(double value)
{
    return (uint8_t)(value / 0.5);
}

double ext_log_data_obstacle_data_b_obstacle_length_decode(uint8_t value)
{
    return ((double)value * 0.5);
}

bool ext_log_data_obstacle_data_b_obstacle_length_is_in_range(uint8_t value)
{
    return (value <= 63u);
}

uint8_t ext_log_data_obstacle_data_b_obstacle_width_encode(double value)
{
    return (uint8_t)(value / 0.05);
}

double ext_log_data_obstacle_data_b_obstacle_width_decode(uint8_t value)
{
    return ((double)value * 0.05);
}

bool ext_log_data_obstacle_data_b_obstacle_width_is_in_range(uint8_t value)
{
    return (value <= 250u);
}

uint8_t ext_log_data_obstacle_data_b_obstacle_age_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_obstacle_data_b_obstacle_age_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_obstacle_data_b_obstacle_age_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ext_log_data_obstacle_data_b_obstacle_lane_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_obstacle_data_b_obstacle_lane_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_obstacle_data_b_obstacle_lane_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t ext_log_data_obstacle_data_b_cipv_flag_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_obstacle_data_b_cipv_flag_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_obstacle_data_b_cipv_flag_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint16_t ext_log_data_obstacle_data_b_radar_pos_x_encode(double value)
{
    return (uint16_t)(value / 0.0625);
}

double ext_log_data_obstacle_data_b_radar_pos_x_decode(uint16_t value)
{
    return ((double)value * 0.0625);
}

bool ext_log_data_obstacle_data_b_radar_pos_x_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

int16_t ext_log_data_obstacle_data_b_radar_vel_x_encode(double value)
{
    return (int16_t)(value / 0.0625);
}

double ext_log_data_obstacle_data_b_radar_vel_x_decode(int16_t value)
{
    return ((double)value * 0.0625);
}

bool ext_log_data_obstacle_data_b_radar_vel_x_is_in_range(int16_t value)
{
    return ((value >= -2048) && (value <= 2048));
}

uint8_t ext_log_data_obstacle_data_b_radar_match_confidence_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_obstacle_data_b_radar_match_confidence_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_obstacle_data_b_radar_match_confidence_is_in_range(uint8_t value)
{
    return (value <= 5u);
}

uint8_t ext_log_data_obstacle_data_b_matched_radar_id_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_obstacle_data_b_matched_radar_id_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_obstacle_data_b_matched_radar_id_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int ext_log_data_obstacle_data_a_pack(
    uint8_t *dst_p,
    const struct ext_log_data_obstacle_data_a_t *src_p,
    size_t size)
{
    uint16_t obstacle_pos_y;
    uint16_t obstacle_vel_x;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->obstacle_id, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->obstacle_pos_x, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->obstacle_pos_x, 8u, 0x0fu);
    obstacle_pos_y = (uint16_t)src_p->obstacle_pos_y;
    dst_p[3] |= pack_left_shift_u16(obstacle_pos_y, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(obstacle_pos_y, 8u, 0x03u);
    dst_p[4] |= pack_left_shift_u8(src_p->blinker_info, 2u, 0x1cu);
    dst_p[4] |= pack_left_shift_u8(src_p->cut_in_and_out, 5u, 0xe0u);
    obstacle_vel_x = (uint16_t)src_p->obstacle_vel_x;
    dst_p[5] |= pack_left_shift_u16(obstacle_vel_x, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(obstacle_vel_x, 8u, 0x0fu);
    dst_p[6] |= pack_left_shift_u8(src_p->obstacle_type, 4u, 0x70u);
    dst_p[7] |= pack_left_shift_u8(src_p->obstacle_status, 0u, 0x07u);
    dst_p[7] |= pack_left_shift_u8(src_p->obstacle_brake_lights, 3u, 0x08u);
    dst_p[7] |= pack_left_shift_u8(src_p->obstacle_valid, 6u, 0xc0u);

    return (8);
}

int ext_log_data_obstacle_data_a_unpack(
    struct ext_log_data_obstacle_data_a_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t obstacle_pos_y;
    uint16_t obstacle_vel_x;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->obstacle_id |= unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->obstacle_pos_x |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->obstacle_pos_x |= unpack_left_shift_u16(src_p[2], 8u, 0x0fu);
    obstacle_pos_y = 0u;
    obstacle_pos_y |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    obstacle_pos_y |= unpack_left_shift_u16(src_p[4], 8u, 0x03u);

    if ((obstacle_pos_y & (1u << 9)) != 0u) {
        obstacle_pos_y |= 0xfc00u;
    }

    dst_p->obstacle_pos_y = (int16_t)obstacle_pos_y;
    dst_p->blinker_info |= unpack_right_shift_u8(src_p[4], 2u, 0x1cu);
    dst_p->cut_in_and_out |= unpack_right_shift_u8(src_p[4], 5u, 0xe0u);
    obstacle_vel_x = 0u;
    obstacle_vel_x |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    obstacle_vel_x |= unpack_left_shift_u16(src_p[6], 8u, 0x0fu);

    if ((obstacle_vel_x & (1u << 11)) != 0u) {
        obstacle_vel_x |= 0xf000u;
    }

    dst_p->obstacle_vel_x = (int16_t)obstacle_vel_x;
    dst_p->obstacle_type |= unpack_right_shift_u8(src_p[6], 4u, 0x70u);
    dst_p->obstacle_status |= unpack_right_shift_u8(src_p[7], 0u, 0x07u);
    dst_p->obstacle_brake_lights |= unpack_right_shift_u8(src_p[7], 3u, 0x08u);
    dst_p->obstacle_valid |= unpack_right_shift_u8(src_p[7], 6u, 0xc0u);

    return (0);
}

uint8_t ext_log_data_obstacle_data_a_obstacle_id_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_obstacle_data_a_obstacle_id_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_obstacle_data_a_obstacle_id_is_in_range(uint8_t value)
{
    return (value <= 63u);
}

uint16_t ext_log_data_obstacle_data_a_obstacle_pos_x_encode(double value)
{
    return (uint16_t)(value / 0.0625);
}

double ext_log_data_obstacle_data_a_obstacle_pos_x_decode(uint16_t value)
{
    return ((double)value * 0.0625);
}

bool ext_log_data_obstacle_data_a_obstacle_pos_x_is_in_range(uint16_t value)
{
    return (value <= 4000u);
}

int16_t ext_log_data_obstacle_data_a_obstacle_pos_y_encode(double value)
{
    return (int16_t)(value / 0.0625);
}

double ext_log_data_obstacle_data_a_obstacle_pos_y_decode(int16_t value)
{
    return ((double)value * 0.0625);
}

bool ext_log_data_obstacle_data_a_obstacle_pos_y_is_in_range(int16_t value)
{
    return ((value >= -512) && (value <= 511));
}

uint8_t ext_log_data_obstacle_data_a_blinker_info_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_obstacle_data_a_blinker_info_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_obstacle_data_a_blinker_info_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t ext_log_data_obstacle_data_a_cut_in_and_out_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_obstacle_data_a_cut_in_and_out_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_obstacle_data_a_cut_in_and_out_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

int16_t ext_log_data_obstacle_data_a_obstacle_vel_x_encode(double value)
{
    return (int16_t)(value / 0.0625);
}

double ext_log_data_obstacle_data_a_obstacle_vel_x_decode(int16_t value)
{
    return ((double)value * 0.0625);
}

bool ext_log_data_obstacle_data_a_obstacle_vel_x_is_in_range(int16_t value)
{
    return ((value >= -2046) && (value <= 2046));
}

uint8_t ext_log_data_obstacle_data_a_obstacle_type_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_obstacle_data_a_obstacle_type_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_obstacle_data_a_obstacle_type_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t ext_log_data_obstacle_data_a_obstacle_status_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_obstacle_data_a_obstacle_status_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_obstacle_data_a_obstacle_status_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t ext_log_data_obstacle_data_a_obstacle_brake_lights_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_obstacle_data_a_obstacle_brake_lights_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_obstacle_data_a_obstacle_brake_lights_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ext_log_data_obstacle_data_a_obstacle_valid_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_obstacle_data_a_obstacle_valid_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_obstacle_data_a_obstacle_valid_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

int ext_log_data_obstacle_status_pack(
    uint8_t *dst_p,
    const struct ext_log_data_obstacle_status_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 7);

    dst_p[0] |= pack_left_shift_u8(src_p->num_obstacles, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->timestamp, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->application_version, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->active_version_number_section, 0u, 0x03u);
    dst_p[3] |= pack_left_shift_u8(src_p->left_close_range_cut_in, 2u, 0x04u);
    dst_p[3] |= pack_left_shift_u8(src_p->right_close_range_cut_in, 3u, 0x08u);
    dst_p[3] |= pack_left_shift_u8(src_p->go, 4u, 0xf0u);
    dst_p[4] |= pack_left_shift_u8(src_p->protocol_version, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->failsafe, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->failsafe, 8u, 0x1fu);
    dst_p[6] |= pack_left_shift_u8(src_p->close_car, 5u, 0x20u);

    return (7);
}

int ext_log_data_obstacle_status_unpack(
    struct ext_log_data_obstacle_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->num_obstacles |= unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->timestamp |= unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->application_version |= unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->active_version_number_section |= unpack_right_shift_u8(src_p[3], 0u, 0x03u);
    dst_p->left_close_range_cut_in |= unpack_right_shift_u8(src_p[3], 2u, 0x04u);
    dst_p->right_close_range_cut_in |= unpack_right_shift_u8(src_p[3], 3u, 0x08u);
    dst_p->go |= unpack_right_shift_u8(src_p[3], 4u, 0xf0u);
    dst_p->protocol_version |= unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->failsafe |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->failsafe |= unpack_left_shift_u16(src_p[6], 8u, 0x1fu);
    dst_p->close_car |= unpack_right_shift_u8(src_p[6], 5u, 0x20u);

    return (0);
}

uint8_t ext_log_data_obstacle_status_num_obstacles_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_obstacle_status_num_obstacles_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_obstacle_status_num_obstacles_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ext_log_data_obstacle_status_timestamp_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_obstacle_status_timestamp_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_obstacle_status_timestamp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ext_log_data_obstacle_status_application_version_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_obstacle_status_application_version_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_obstacle_status_application_version_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ext_log_data_obstacle_status_active_version_number_section_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_obstacle_status_active_version_number_section_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_obstacle_status_active_version_number_section_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t ext_log_data_obstacle_status_left_close_range_cut_in_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_obstacle_status_left_close_range_cut_in_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_obstacle_status_left_close_range_cut_in_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ext_log_data_obstacle_status_right_close_range_cut_in_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_obstacle_status_right_close_range_cut_in_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_obstacle_status_right_close_range_cut_in_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ext_log_data_obstacle_status_go_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_obstacle_status_go_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_obstacle_status_go_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t ext_log_data_obstacle_status_protocol_version_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_obstacle_status_protocol_version_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_obstacle_status_protocol_version_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint16_t ext_log_data_obstacle_status_failsafe_encode(double value)
{
    return (uint16_t)(value);
}

double ext_log_data_obstacle_status_failsafe_decode(uint16_t value)
{
    return ((double)value);
}

bool ext_log_data_obstacle_status_failsafe_is_in_range(uint16_t value)
{
    return (value <= 8191u);
}

uint8_t ext_log_data_obstacle_status_close_car_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_obstacle_status_close_car_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_obstacle_status_close_car_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int ext_log_data_high_low_beam_pack(
    uint8_t *dst_p,
    const struct ext_log_data_high_low_beam_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 3);

    dst_p[0] |= pack_left_shift_u8(src_p->binary_high_low_beam_decision, 0u, 0x03u);
    dst_p[1] |= pack_left_shift_u16(src_p->reasons_to_switch_to_low_beam, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->reasons_to_switch_to_low_beam, 8u, 0x01u);

    return (3);
}

int ext_log_data_high_low_beam_unpack(
    struct ext_log_data_high_low_beam_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->binary_high_low_beam_decision |= unpack_right_shift_u8(src_p[0], 0u, 0x03u);
    dst_p->reasons_to_switch_to_low_beam |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->reasons_to_switch_to_low_beam |= unpack_left_shift_u16(src_p[2], 8u, 0x01u);

    return (0);
}

uint8_t ext_log_data_high_low_beam_binary_high_low_beam_decision_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_high_low_beam_binary_high_low_beam_decision_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_high_low_beam_binary_high_low_beam_decision_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint16_t ext_log_data_high_low_beam_reasons_to_switch_to_low_beam_encode(double value)
{
    return (uint16_t)(value);
}

double ext_log_data_high_low_beam_reasons_to_switch_to_low_beam_decode(uint16_t value)
{
    return ((double)value);
}

bool ext_log_data_high_low_beam_reasons_to_switch_to_low_beam_is_in_range(uint16_t value)
{
    return (value <= 511u);
}

int ext_log_data_vision_only_tsr_continues_pack(
    uint8_t *dst_p,
    const struct ext_log_data_vision_only_tsr_continues_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->vision_only_sign_type_d1, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->vision_only_supp_sign_type_d1, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->vision_only_sign_type_d2, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->vision_only_supp_sign_type_d2, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->vision_only_sign_type_d3, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->vision_only_supp_sign_type_d3, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->vision_only_sign_type_d4, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->vision_only_supp_sign_type_d4, 0u, 0xffu);

    return (8);
}

int ext_log_data_vision_only_tsr_continues_unpack(
    struct ext_log_data_vision_only_tsr_continues_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->vision_only_sign_type_d1 |= unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->vision_only_supp_sign_type_d1 |= unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->vision_only_sign_type_d2 |= unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->vision_only_supp_sign_type_d2 |= unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->vision_only_sign_type_d3 |= unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->vision_only_supp_sign_type_d3 |= unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->vision_only_sign_type_d4 |= unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->vision_only_supp_sign_type_d4 |= unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

uint8_t ext_log_data_vision_only_tsr_continues_vision_only_sign_type_d1_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_vision_only_tsr_continues_vision_only_sign_type_d1_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_vision_only_tsr_continues_vision_only_sign_type_d1_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ext_log_data_vision_only_tsr_continues_vision_only_supp_sign_type_d1_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_vision_only_tsr_continues_vision_only_supp_sign_type_d1_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_vision_only_tsr_continues_vision_only_supp_sign_type_d1_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ext_log_data_vision_only_tsr_continues_vision_only_sign_type_d2_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_vision_only_tsr_continues_vision_only_sign_type_d2_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_vision_only_tsr_continues_vision_only_sign_type_d2_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ext_log_data_vision_only_tsr_continues_vision_only_supp_sign_type_d2_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_vision_only_tsr_continues_vision_only_supp_sign_type_d2_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_vision_only_tsr_continues_vision_only_supp_sign_type_d2_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ext_log_data_vision_only_tsr_continues_vision_only_sign_type_d3_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_vision_only_tsr_continues_vision_only_sign_type_d3_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_vision_only_tsr_continues_vision_only_sign_type_d3_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ext_log_data_vision_only_tsr_continues_vision_only_supp_sign_type_d3_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_vision_only_tsr_continues_vision_only_supp_sign_type_d3_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_vision_only_tsr_continues_vision_only_supp_sign_type_d3_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ext_log_data_vision_only_tsr_continues_vision_only_sign_type_d4_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_vision_only_tsr_continues_vision_only_sign_type_d4_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_vision_only_tsr_continues_vision_only_sign_type_d4_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ext_log_data_vision_only_tsr_continues_vision_only_supp_sign_type_d4_encode(double value)
{
    return (uint8_t)(value);
}

double ext_log_data_vision_only_tsr_continues_vision_only_supp_sign_type_d4_decode(uint8_t value)
{
    return ((double)value);
}

bool ext_log_data_vision_only_tsr_continues_vision_only_supp_sign_type_d4_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}
