uint8[9] me_lane_type_L
uint8[9] me_lane_quality_L
float64[9] me_lane_position_L
float64[9] me_lane_curvature_L
float64[9] me_lane_curvature_derivative_L
float64[9] me_lane_heading_angle_L

uint8[9] me_lane_type_R
uint8[9] me_lane_quality_R
float64[9] me_lane_position_R
float64[9] me_lane_curvature_R
float64[9] me_lane_curvature_derivative_R
float64[9] me_lane_heading_angle_R

float64 me_timestamp
uint8[10] me_lane
